### ISSUE TITLE
Wrench shift-right click picks up all blocks

### ISSUE THREAD

**Issue by nanakisan** [TeamMonumental/FusionWarfare#1]
At 1st I thought this was an intended feature. But your mods wrench is capable of completely overriding the need for a pickaxe! I can literally shift-right click any block and bam, it's now dropped and on the ground.  
  
So yeah I don't know if this is intended behavior or not. But this is a absolutely balance breaker.

**Comment by TeamMonumental** [comment]
Is this happening to every block, or just the tile entities added by this mod (cables, machines, etc.)? If it isn't, this is an intended feature. Mainly used to store FE in the machines for easy transport.

**Comment by nanakisan** [comment]
at the time of this posting it was every single block, vanilla and modded.

**Comment by TeamMonumental** [comment]
Thanks for the report. The fix will be in the next update.
