### ISSUE TITLE
items not stacking after breaking them!

### ISSUE THREAD

**Issue by MagicMech299** [TeamMonumental/FusionWarfare#2]
When i place a block from a stack and then break it, it creates its own stack and it has the same id but it won't stack with the old stack anymore.

I do have other mods!
After hours of removing and replacing mods in the modpack i realized your mod is the one causing it.

P.S. I realy like your mod its great and i hope you continue to update it!

**Comment by TeamMonumental** [comment]
We have actually came across this bug while fixing the others. It should be resolved in the next update. Thanks for the report.
