### ISSUE TITLE
Supply Crates spamming on event (Extra Utilities).

### ISSUE THREAD

**Issue by ProxyPlayerHD** [TeamMonumental/FusionWarfare#2]
I just played with this Mod and suddenly the Chat goes nuts and kept telling me that a supply-chest were fallen from the sky. after some time it stoped and i found the place where they fallen. I don't think the chests should be that common, they also should break (no matter if Items are in there or not) when you close the chest GUI...

here is a picture of the "Field of Spam"
![2015-07-30_20 51 21](https://cloud.githubusercontent.com/assets/13576843/8992363/577f6d22-36fe-11e5-9f38-540bb8866452.png)

I hope this helps finding the problem!

**Comment by TeamMonumental** [comment]
Thanks for the report. If you could, posting the mods you have installed would be very helpful.

**Comment by ProxyPlayerHD** [comment]
here is a list of the Mods a use (most of them are on the newest version):
Applied Energistics 2
Big Reactors
Blood Magic
Buildcraft (+Buildcraft Compat)
Carpenter's Blocks
Chisel 2
Code Chicken Core
CoFH Core
Cookie Core
Draconic Evolution
DragonAPI
EnderIO
Extra Utilities
Factorization
Fastcraft
Fast Leaf Decay
Fusion Warfare
iChunUtil
Inventory Tweaks
Ironchest
Journey Map
Mantle
Mekanism (+MekanismGenerators, +MekanismTools)
MinefactoryReloaded
NEI (+NEIaddons, +NotEnoughCodes, +NotEnoughKeys, +NotEnoughResources)
Optifine
Portal Gun
Railcraft
Redstone Arsenal
RFTools
Simply Jetpacks
Solar Expansion
Solar Flux
TConstruct (+TiCTooltips)
ttCore
Vein Miner
Waila (+WailaHarvestability, +WailaPlugins, +Wawla)

**Comment by TeamMonumental** [comment]
We have tested all the mods and narrowed it down to the Extra Utilities mod. It conflicts with our time event. We are trying our best to fix the problem.

**Comment by TeamMonumental** [comment]
We have fixed the issue, which will be in the next update (v1.0.1). Thanks for the report, it helped a lot.
